### PR TITLE
NPE fix of new experimental option (Issue #9), new customizable entity blacklist and fix new crash with latest Paper releases

### PR DESCRIPTION
**Pull request by rayanbzd**
Some worlds may not be loaded when loading world cache on enable. (With plugins like Multiverse-Core)

Here is the patched jar for testing: https://assets.zencraft.fr/EntityTrackerFixer.jar

### CODE REVIEW

**Comment by rayanbzd** [comment]
Warning /!\ I updated the patch for fix this other NPE: 

`[EntityTrackerFixer] Task #16 for EntityTrackerFixer v1.2.3 generated an exception
java.lang.NullPointerException: null
	at net.minemora.entitytrackerfixer.v1_15_R1.entityTick.EntityTickManager.enableTicking(EntityTickManager.java:44) ~[?:?]
	at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:45) ~[?:?]
	at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-155]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-155]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

Please make sure to re-download the jar available on the link above for testing.

**Comment by rayanbzd** [comment]
Just added a customizable entity blacklist that should not be impacted by the plugin. 
Delete your old configuration file before update to the testing jar. 
I updated the jar available on my first post above.

**Comment by rayanbzd** [comment]
Just fixed new spam on console and crashs with latests paper releases (appear at build 155 and causing crash at build 158).
Updated the jar available on my first post above.

**Comment by HexedHero** [comment]
@Esmorall

**Comment by JavierKasunic** [comment]
> @Esmorall

Mentioning him does nothing, he already receives notifications for every comment there is on an issue

**Comment by Elric02** [comment]
Thanks a lot Futurixel

**Pull request closed without merging**
