### PR TITLE
Added support for 1.17 (and older versions of 1.16) + Things related to the ETF command.

### PR DESCRIPTION
**Pull request by cascaseno**
**ENGLISH / INGLÉS:**

Added support for 1.17 (and older 1.16 versions like 1.16.3, 1.16.2, 1.16.1 and 1.16).

Changes between the official version and mine (1.3.4_Unofficial):
+ Added support for **1.17**.
+ Added again support for older 1.16.
+ Added error message if "/etf" command is used without arguments.
+ Added error message if "/etf" command arguments are not valid.

Compiled plugin file download link (1.3.4_Unofficial): https://unserversinley.net/misc/jars/EntityTrackerFixer-1.17.jar
Compiled on IntelliJ IDEA.

Have a nice day ^^

**SPANISH / ESPAÑOL:**

Añadido soporte para la 1.17 (y versiones antiguas de la 1.16 como la 1.16.3, 1.16.2, 1.16.1 y 1.16).

Cambios entre la versión oficial y la mía (1.3.4_Unofficial):
+ Añadido soporte para la **1.17**.
+ Añadido otra vez soporte para versiones antiguas de la 1.16.
+ Añadido mensaje de error si el comando "/etf" se usa sin argumentos.
+ Añadido mensaje de error si el comando "/etf" se usa con argumentos no válidos.

Link de descarga del plugin compilado (1.3.4_Unofficial): https://unserversinley.net/misc/jars/EntityTrackerFixer-1.17.jar
Compilado en IntelliJ IDEA.

Ten un buen día ^^

### CODE REVIEW

**Review by Feriixu — APPROVED** [review]
I see no malicious code. I'd say it's safe to merge.

**Comment by Apprisco** [comment]
On the other hand, I suggest not merging.
I've noticed that some mobs, especially tamed pets, lose all AI except teleportation with the 1.17 version of the plugin.
No issues without.
Restarting did not fix the issue at all, and even after uninstalling, mobs had to be killed.

**Comment by cascaseno** [comment]
Thanks for your comment, can you try the same in 1.16 with the official version of the plugin and tell me if it happens? Also, are you using spigot or paper? If there's any error on console let me know, Mojang changed a few things between 1.16 and 1.17 that may have affected the plugin.

Also, remember that I am not the original creator of the plugin, this is an attempt to help the creator and to help some people to have the plugin in 1.17 while there is no official version. Regards, cascaseno.

**Comment by cascaseno** [comment]
I've updated the compiled plugin download link to show a warning before downloading.

**Comment by Apprisco** [comment]
> Thanks for your comment, can you try the same in 1.16 with the official version of the plugin and tell me if it happens? Also, are you using spigot or paper? If there's any error on console let me know, Mojang changed a few things between 1.16 and 1.17 that may have affected the plugin.
> 
> Also, remember that I am not the original creator of the plugin, this is an attempt to help the creator and to help some people to have the plugin in 1.17 while there is no official version. Regards, cascaseno.

I know, thanks for all the work.
I think entity lag isn't too bad in 1.17 right now except for GOATs.
Screw goats.
In 1.16, the issue never happens.
There are no errors in the console, and I'm using Paper. It doesn't work on Paper & Purpur & Tunity from what I can tell.
Mojang changed a ton of enums, maybe that's why?

**Comment by cascaseno** [comment]
> > Thanks for your comment, can you try the same in 1.16 with the official version of the plugin and tell me if it happens? Also, are you using spigot or paper? If there's any error on console let me know, Mojang changed a few things between 1.16 and 1.17 that may have affected the plugin.
> > Also, remember that I am not the original creator of the plugin, this is an attempt to help the creator and to help some people to have the plugin in 1.17 while there is no official version. Regards, cascaseno.
> 
> I know, thanks for all the work.
> I think entity lag isn't too bad in 1.17 right now except for GOATs.
> Screw goats.
> In 1.16, the issue never happens.
> There are no errors in the console, and I'm using Paper. It doesn't work on Paper & Purpur & Tunity from what I can tell.
> Mojang changed a ton of enums, maybe that's why?

I didn't do much either, it's the 1_16_R3 code adapted to 1.17.

Apart from that, I was looking and it seems that now Minecraft saves the entities in a separate folder, not in the region files. Look for a 1.17 world and you will see that now (apart from the region, poi,... folders) there is a folder called "entities". Definitely, Mojang has changed something regarding the entities, and this may be affecting the plugin.

The frozen entities thing happened to me on my test server with the very first 1.17 paper releases, but I don't really know how to recreate it, so any information is welcome.

Thanks for your comment, and I'm sorry if my version of the plugin has caused problems on your server.
Regards, cascaseno.

**Comment by cascaseno** [comment]
I've been testing the plugin on the latest versions of Paper and have not seen the bug occur again.

Also, this last commit doesn't change anything related to this, it doesn't change anything actually, I think it just changes a few spaces and tabulations.

I made a new compilation (**Hotfix1**) available at the same link (https://unserversinley.net/misc/jars/EntityTrackerFixer-1.17.jar) that I think doesn't change anything, but it's the one I've been using for these last tests and it seems (but I don't assure) that it works fine.

As I said, I've used the latest versions of Paper to test it (the 69 one 😳, specifically).
If you want, try this version with the latest paper builds and comment if it still happens.

Regards, cascaseno.

**Comment by pokemonrocks9** [comment]
It appears to have removed the AI of my servers mobs again atleast all non hostile mobs like Bees Villagers and Golems have been affected

**Comment by cascaseno** [comment]
> It appears to have removed the AI of my servers mobs again atleast all non hostile mobs like Bees Villagers and Golems have been affected

Are you using Paper, Spigot, Bukkit...? If you can, tell me the exact version (for example: git-Paper-75)
You can see this by writting "/ver" in your server.

Also, if you see any errors in console let me know. As always, remember that I'm not the original creator of the plugin, **I'm just trying to help**.

Test the plugin well before adding it to your final server, I've been testing it and I am not able to recreate the issue at least with the latest Paper builds.

Regards, cascaseno.

**Comment by pokemonrocks9** [comment]
Paper Though that could be why it doesnt seem to update on my provider allow me to check into that.

**Comment by st4rburn** [comment]
Can confirm I've had a similar issue on my server
I was using Paper build 69 (until updating to 90 today for 1.17.1 without the plugin enabled) so, although I'm also not sure how to recreate the issue entirely, I can confirm it exists on build 69
I'm currently in the process of testing and fixing the issue on my server so I'm going to keep editing this comment with my results
Some players noticed the issue seemed to be per-chunk and although I can't confirm that, it seemed to add up from the entities that were working and those that weren't
~~Also considering villagers at stalls can still restock, plus I believe (I'll have to check though) sheep can eat grass, I'd say that the issue is not so much AI but specifically pathfinding~~ (check below)
My assumption is that this is happening to entities that are being untracked but I'm checking this now

Build 69 (1.17) with plugin (original): Causes frozen entities
Build 69 (1.17) removed plugin: Entities still frozen but no new ones
Build 90 (1.17.1) removed plugin: Entities still frozen but no new ones
Build 90 (1.17.1) with plugin (hotfix): Causes frozen entities

I can't go back to 1.17 because the world has been saved in 1.17.1 now (I have backups but it's getting close to 1am so I may not do a lot more testing tonight)

Interesting development: Some of my players went though a phase of boating creepers and leaving them there 😂 and some of these creepers seem to have lost the ability to explode (so are showing the same issue)
This may disprove that the issue is pathfinding though

Anyway it is getting late for me so my plan is to find a way to fix broken entities then remove the plugin for now
I may do some further testing later and if I write plugin code to fix the broken entities I'll post it here

**Comment by cascaseno** [comment]
Thank you very much for your comment!

I think I've found the error. The "**ChunkLoadEvent**" event in the "**EntityTickManager.java**" file does not work in 1.17, but it does in older MC versions (like 1.16, etc...).

I do not know why this event does not work, the code seems fine to me. I'll take a look and see if I'm able to fix it.

That's the bug for sure.

**Comment by cascaseno** [comment]
Thank you very much for your comment!

I've been testing and seems that setting the "**disable-tick-for-untracked-entities**" option to "**false**" in the plugin config may fix this issue.

If you can, try the plugin with that option disabled and see if it still happens.

Regards, cascaseno.

**Comment by cascaseno** [comment]
Ok, I've found the problem and will try to explain it in as much detail as possible.

**I'm not sure if the plugin works at all like this, but I think it does.**

When the plugin has the "**disable-tick-for-untracked-entities**" setting set to "true", it enables this class file:
image

This class has **some important things** to point out:

image
The "disableTicking" method is called when the entities are untracked by the plugin, and what it does is basically disabling all the untracked entities AI (pathfinding, etc,...) to reduce lag (which is the goal of the plugin).

This gets all the untracked entities and disables it's AI / ticking. `((EntityInsentient)entity).aware = false;`

When the player gets near to the untracked entities, their ticking (AI) needs to be enabled again, and that leads us to a method, which is called to enable all the untracked entities AI again and has nothing to do with what I'm going to say next.

**The problem:**

When you shutdown the server, the entities that are **still untracked and without AI** are saved like that, and on the next server startup they will be loaded also without AI. To fix this problem, what Esmorall (now called Elecast2) did was add this event to the code:

image

When a player loads a chunk (ChunkLoadEvent) the server gets all the entities that are on that chunk `for(Entity entity : event.getChunk().getEntities()) {}` and if they have the AI disabled, it enables it `if(!((EntityInsentient)nms).aware) ((EntityInsentient) nms).aware = true;`

The thing here is that it seems that in 1.17, bukkit (and spigot, paper, etc...) has a **bug** which says that in that chunk there are no entities regardless of whether there are or not (basically, the `event.getChunk().getEntities()` is **always null**.

Here you have a **direct comparision**:
**1.17**: 
image

1.16 (and older):
image

The "good news" is that the "**ChunkUnloadEvent**" seems to work fine in 1.17, so the (probably) easiest solution to implement right now would be, in my opinion, that instead of **returning AI to mobs when the server LOADS chunks**, it would be **doing it when they get UNLOADED**.

**This could still leave some frozen entities** BUT they would **not be permanently frozen**. For instance, let's say that a player **LOADS a chunk with frozen entities**, **unloads it**, and when they **load again the chunk** (in theory) there should be no frozen entities.

The **EASIER FIX** you can do to fix the **freezing problem** in your server is set the setting "**disable-tick-for-untracked-entities**" to "**false**" in the plugin config.

Maybe there's an easy fix, but for now I'll be doing some testings on this and I'll tell you the results.

Regards, cascaseno.

**Comment by cascaseno** [comment]
By the way, this would be a **temporary solution** that would still leave some frozen entities. This should only be used while the Bukkit bug is not fixed. It should work **but not perfectly**.

I am sure there is a better way to fix it and will investigate to find a better way to do it.

**Comment by franxyk** [comment]
you no longer have any problem? is it safe to use?

**Comment by CloudeLecaw** [comment]
cascaseno  sais it i can agree it

We had some entities that become freezen (no AI anmyore) from it forever...
PaperMC 1.17.1

**Comment by cascaseno** [comment]
> you no longer have any problem? is it safe to use?

Hi, first of all, have you used the plugin before? If you have used it before, see if you have in the config the option "**disable-tick-for-untracked-entities**" set to "**true**", since that may cause problems.

**Comment by cascaseno** [comment]
> cascaseno sais it i can agree it
> 
> We had some entities that become freezen (no AI anmyore) from it forever...
> PaperMC 1.17.1

When I tried the update, I did it with an option disabled in the config, which seems to be causing problems on 1.17 and up if it's enabled.

I've already explained the problem above, but basically, Mojang changed things regarding entities and Bukkit has a bug (probably due to that) that causes a bug in this plugin in versions higher than 1.16.5 (that is, 1.17 and 1.17.1).

Those entities can be unfreeze for sure, I'm working on a fix.

**Comment by CloudeLecaw** [comment]
Hmm we had option "disable-tick-for-untracked-entities" set to "false" in config allready...
Strange..so it means it was still freezing them? :3 (not all, just some) andnyes like u wrote before also in our case the chance is high that we restarted the server (we also setted it to restart once a day)

**Comment by cascaseno** [comment]
> Hmm we had option "disable-tick-for-untracked-entities" set to "false" in config allready...
> Strange..so it means it was still freezing them? :3 (not all, just some) andnyes like u wrote before also in our case the chance is high that we restarted the server (we also setted it to restart once a day)

Did you ever have that option enabled? For example, maybe in 1.16 you had it and you disabled it for 1.17.

**Comment by CloudeLecaw** [comment]
note i had allways set it to false because of this note:
`# Note 2: this option is experimental and could contain errors`

We are a live server so experimental options are mostly no good choice :3

**Comment by cascaseno** [comment]
> note i had allways set it to false because of this note:
> `# Note 2: this option is experimental and could contain errors`
> 
> We are a live server so experimental options are mostly no good choice :3

I find it strange that entities are also frozen with that option disabled. One thing, how many entities were frozen aproximately, I mean, a lot or just a few?

**Comment by CloudeLecaw** [comment]
You could say a few, the chunks where we noticed it first, belonges to a player region and has many animal stalls with about 11 chickens, 6 cows, 4 pigs, 5 parrots, 6 white foxes, 6 red foxes, 2 horses, 7 sheeps, 6 pandas and 4 axalots. The first time we saw it most foxes of it, most chickens, 2 cows, 3 pigs, the dogs and the pandas were frozen..so you could say  a lot. We replaced all for the player. The secound time just 3/4 of the foxes, one pig and 2 cows were frozen. (That was about 12 hours later after we replaced them)
Flying around the world we sometimes noticed a single sheep or a single chicken that lost its Ai. So you could say regulary just a few, but if the chunks contains a lot of living entites, then the chance is higer to be a lot are effected.

**Comment by cascaseno** [comment]
> You could say a few, the chunks where we noticed it first, belonges to a player region and has many animal stalls with about 11 chickens, 6 cows, 4 pigs, 5 parrots, 6 white foxes, 6 red foxes, 2 horses, 7 sheeps, 6 pandas and 4 axalots. The first time we saw it most foxes of it, most chickens, 2 cows, 3 pigs, the dogs and the pandas were frozen..so you could say a lot. We replaced all for the player. The secound time just 3/4 of the foxes, one pig and 2 cows were frozen. (That was about 12 hours later after we replaced them)
> Flying around the world we sometimes noticed a single sheep or a single chicken that lost its Ai. So you could say regulary just a few, but if the chunks contains a lot of living entites, then the chance is higer to be a lot are effected.

Ok, for now I would recommend removing the plugin.

If a lot of entities have been frozen and you need to unfreeze them, I am working on a tool for it.
Thank you very much for your comment.

**Comment by JeffP07** [comment]
@cascaseno this seems to be due to this bug: https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6547?filter=allopenissues so in theory it should work again once the PR gets accepted and rolled in

**Comment by JeffP07** [comment]
As for something to fix frozen entities, I created a quick and dirty plugin here: https://github.com/Boothin/aware-fixer/releases

all it does is go through all the entities in your current chunk and reset the bukkit.aware flag on them when you run the command

**Comment by cascaseno** [comment]
> As for something to fix frozen entities, I created a quick and dirty plugin here: https://github.com/Boothin/aware-fixer/releases
> 
> all it does is go through all the entities in your current chunk and reset the bukkit.aware flag on them when you run the command

Thanks for comment ^^

I did something similar for a server that had problems with entities that were frozen by the plugin. In case anyone is interested, I will leave it here. You can download it compiled in the releases. https://github.com/cascaseno/ETFUnfreezer

**Comment by srnyx** [comment]
@cascaseno Could you make a Releases page on the Pull Request repository and post the releases there? That way people can Watch it and get alerted if you update it.

**Comment by cascaseno** [comment]
> @cascaseno Could you make a Releases page on the Pull Request repository and post the releases there? That way people can Watch it and get alerted if you update it.

Good idea, I'll do it if I make any changes.

By the way, if you are going to download the 1.17 plugin to use it on a server, keep in mind that there is a bug that **freezes entities**. I personally don't recommend using the plugin on 1.17+ servers, some entities will freeze for sure.

**Comment by srnyx** [comment]
> By the way, if you are going to download the 1.17 plugin to use it on a server, keep in mind that there is a bug that **freezes entities**. I personally don't recommend using the plugin on 1.17+ servers, some entities will freeze for sure.

Is there a way to fix it? If so, are you gonna try and fix it?

**Comment by CloudeLecaw** [comment]
Currently u juat can use a tool that offers a commmand to unfrezze them.

https://github.com/cascaseno/ETFUnfreezer

**Comment by Netscape7** [comment]
The plugin download page is no longer available.
I just get a 404 error when I open the link. Help me.

**Comment by cascaseno** [comment]
> The plugin download page is no longer available. I just get a 404 error when I open the link. Help me.

I've made the download unavailable because the update I've made had a bug that was freezing some entities. It was a Bukkit problem, and I don't know if they fixed it or not, but I preferred to remove the download to prevent people from having this freezing entities problem on their servers.

Check this comment for more information https://github.com/Elecast2/EntityTrackerFixer/pull/30#issuecomment-877327933

**Comment by srnyx** [comment]
It's recommended now to not use this plugin altogether and to just let Paper handle entity tracking.

**Pull request closed without merging**
