### PR TITLE
Support for 1.16.4 + Error chat msg if /etf command has 0 args.

### PR DESCRIPTION
**Pull request by cascaseno**
This adds support for version 1.16.4 (1_16_R3), updates README.md and it also adds an error chat message if the /etf command is used with 0 arguments. Added message is "No arguments provided. Available: /etf reload."

Download compiled file here: https://unserversinley.net/misc/jars/EntityTrackerFixer-1.16.4.jar
Have a nice day.

### CODE REVIEW

**Comment by newjebv** [comment]
Thank you very much for that! This is very important, especially for many servers that, like me, depend on this plugin, you are really handsome

**Comment by cascaseno** [comment]
Summary of all those commits: Fixed a typo and added a message that will appear if the arguments provided in the "/etf" command are not valid.

**Comment by cascaseno** [comment]
Summary of all those commits: Fixed a typo and added a chat message that appears if the arguments provided in the "/etf" command are not valid.

**Comment by hvrry** [comment]
Thanks :)

**Comment by s-yh-china** [comment]
Thanks ~

**Comment by TheLucXas** [comment]
doesn't work for 1.16.3 :(

**Comment by cascaseno** [comment]
Ok, I forgot to compile the .jar file with the config inside, sorry about that, I'll update the .jar file.

**Comment by cascaseno** [comment]
**IF THE OLD UNOFFICIAL VERSION DOES NOT WORK FOR YOU, PLEASE RE-DOWNLOAD IT NOW**
I forgot to compile the .jar file with the config inside, sorry about that.

I updated the plugin file, same link, new fixed file.
https://unserversinley.net/misc/jars/EntityTrackerFixer-1.16.4.jar

**Pull request closed without merging**
